### ISSUE TITLE
 Cannot Find BWidget Package

### ISSUE THREAD

**Issue by csucyg** [fpl/polsarpro#1]
Hello，
when I ran the software after installation， an error was displayed:
 "Cannot Find BWidget Package"
Could you help me?
Thank you very much.

Best regards

![QQ图片20240123122010](https://github.com/fpl/polsarpro/assets/57473830/0c04ba2a-74d3-4e9d-b74f-683675d4b88f)

**Comment by fpl** [comment]
On Debian and derivatives you can `apt install bwidget`, which is a Tk package. It is listed in my [README.md](https://github.com/fpl/polsarpro/blob/main/README.md)
